//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
namespace Aspose.ExchangeSync.Data
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class ExchangeSyncEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new ExchangeSyncEntities object using the connection string found in the 'ExchangeSyncEntities' section of the application configuration file.
        /// </summary>
        public ExchangeSyncEntities() : base("name=ExchangeSyncEntities", "ExchangeSyncEntities")
        {
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new ExchangeSyncEntities object.
        /// </summary>
        public ExchangeSyncEntities(string connectionString) : base(connectionString, "ExchangeSyncEntities")
        {
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new ExchangeSyncEntities object.
        /// </summary>
        public ExchangeSyncEntities(EntityConnection connection) : base(connection, "ExchangeSyncEntities")
        {
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Aspose_ExchangeSync_ServerDetails> Aspose_ExchangeSync_ServerDetails
        {
            get
            {
                if ((_Aspose_ExchangeSync_ServerDetails == null))
                {
                    _Aspose_ExchangeSync_ServerDetails = base.CreateObjectSet<Aspose_ExchangeSync_ServerDetails>("Aspose_ExchangeSync_ServerDetails");
                }
                return _Aspose_ExchangeSync_ServerDetails;
            }
        }
        private ObjectSet<Aspose_ExchangeSync_ServerDetails> _Aspose_ExchangeSync_ServerDetails;

        #endregion

        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Aspose_ExchangeSync_ServerDetails EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToAspose_ExchangeSync_ServerDetails(Aspose_ExchangeSync_ServerDetails aspose_ExchangeSync_ServerDetails)
        {
            base.AddObject("Aspose_ExchangeSync_ServerDetails", aspose_ExchangeSync_ServerDetails);
        }

        #endregion

    }

    #endregion

    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="ExchangeSyncModel", Name="Aspose_ExchangeSync_ServerDetails")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Aspose_ExchangeSync_ServerDetails : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Aspose_ExchangeSync_ServerDetails object.
        /// </summary>
        /// <param name="id">Initial value of the ID property.</param>
        public static Aspose_ExchangeSync_ServerDetails CreateAspose_ExchangeSync_ServerDetails(global::System.Int32 id)
        {
            Aspose_ExchangeSync_ServerDetails aspose_ExchangeSync_ServerDetails = new Aspose_ExchangeSync_ServerDetails();
            aspose_ExchangeSync_ServerDetails.ID = id;
            return aspose_ExchangeSync_ServerDetails;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ID
        {
            get
            {
                return _ID;
            }
            set
            {
                if (_ID != value)
                {
                    OnIDChanging(value);
                    ReportPropertyChanging("ID");
                    _ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ID");
                    OnIDChanged();
                }
            }
        }
        private global::System.Int32 _ID;
        partial void OnIDChanging(global::System.Int32 value);
        partial void OnIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String UserID
        {
            get
            {
                return _UserID;
            }
            set
            {
                OnUserIDChanging(value);
                ReportPropertyChanging("UserID");
                _UserID = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("UserID");
                OnUserIDChanged();
            }
        }
        private global::System.String _UserID;
        partial void OnUserIDChanging(global::System.String value);
        partial void OnUserIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ServerURL
        {
            get
            {
                return _ServerURL;
            }
            set
            {
                OnServerURLChanging(value);
                ReportPropertyChanging("ServerURL");
                _ServerURL = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("ServerURL");
                OnServerURLChanged();
            }
        }
        private global::System.String _ServerURL;
        partial void OnServerURLChanging(global::System.String value);
        partial void OnServerURLChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Username
        {
            get
            {
                return _Username;
            }
            set
            {
                OnUsernameChanging(value);
                ReportPropertyChanging("Username");
                _Username = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Username");
                OnUsernameChanged();
            }
        }
        private global::System.String _Username;
        partial void OnUsernameChanging(global::System.String value);
        partial void OnUsernameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Password
        {
            get
            {
                return _Password;
            }
            set
            {
                OnPasswordChanging(value);
                ReportPropertyChanging("Password");
                _Password = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Password");
                OnPasswordChanged();
            }
        }
        private global::System.String _Password;
        partial void OnPasswordChanging(global::System.String value);
        partial void OnPasswordChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Domain
        {
            get
            {
                return _Domain;
            }
            set
            {
                OnDomainChanging(value);
                ReportPropertyChanging("Domain");
                _Domain = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Domain");
                OnDomainChanged();
            }
        }
        private global::System.String _Domain;
        partial void OnDomainChanging(global::System.String value);
        partial void OnDomainChanged();

        #endregion

    
    }

    #endregion

    
}
